
name: develop

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint:fix
    - name: Run all tests
      run: npm run test
    - name: Build
      run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    name: Netlify Actions
    needs: build
    steps:   
    - uses: nwtgck/actions-netlify@v2.0.0
      with:
        # Publish directory
        publish-dir: ./.next
        # Custom deploy message for Netlify
        deploy-message: "Go to God 🚀"
        # GitHub token
        GITHUB-TOKEN: ${{ secrets.GIT_TOKEN }}
        # Production branch 
        production-branch: dev
        # Indicate wether to deploy production build
        production-deploy: dev
        # Enable pull request comment
        enable-pull-request-comment: false
        # Enable commit comment
        enable-commit-comment: true
        # Enable GitHub commit status
        enable-commit-status: true
        # Overwrites pull request comment
        overwrites-pull-request-comment: false
        # Environment name of GitHub Deployments
        github-deployment-environment: dev
        # Description of the GitHub Deployment
        github-deployment-description: developer 
        # Fails if no credentials provided
        fails-without-credentials: true



