
name: develop

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint:fix
    - name: Run all tests
      run: npm run test
   
  teste2e:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: cypress-io/github-action@v5.8.2
    - name:  Cypress.io
      with:
        working-directory: cypress
        wait-on-timeout: 30

  build: 
    needs: teste2e 
    runs-on: ubuntu-latest
    steps:
    - name: generate artifect
      run: npm run build
     
  deploy:
    runs-on: ubuntu-latest
    name: Netlify Actions
    needs: build
    steps:   
    - uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: ./.next
        deploy-message: success deploy
        github-token: ${{secrets.GIT_SECRET}}




