
name: develop

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint:fix
    - name: Run all tests
      run: npm run test
    - name: Build
      run: npm run build
  
  deploy:
   runs-on: ubuntu-latest
   needs: build
   name: Netlify Actions
   steps:
   - uses: nwtgck/actions-netlify@v1.2.4
     with:
      # Publish directory
      publish-dir: ./.next
      # Functions directory
      # Custom deploy message for Netlify
      deploy-message: Bora para cima! 🚀
      # GitHub token
      github-token: ${{ secrets.GIT_TOKEN }}
      netlify-auth-token: ${{ secrets.NET_SECRET }}
      netlify-site-id: ${{ secrets.NET_SITE_ID }}
      # Production branch
      production-branch: dev
      # Indicate wether to deploy production build
      production-deploy: dev
      # Enable pull request comment
      enable-pull-request-comment: false
      # Enable commit comment
      enable-commit-comment: false
      # Enable GitHub commit status
      enable-commit-status: false
      # Overwrites pull request comment
      overwrites-pull-request-comment: false
    

  
