
name: develop

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint:fix
    - name: Run all tests
      run: npm run test
  testse2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: cypress testse2e
      uses: cypress-io/github-action@v5.8.2
      with: 
       command: npm run cy:test
     
  build:
   runs-on: ubuntu-latest
   needs: testse2e
   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: generate artefect
      run: npm run build      
  
  deploy:
     runs-on: ubuntu-latest
     name: Deploy to EBS 🚀
     needs: build
     steps:   
     - uses: nwtgck/actions-netlify@v2.0.0
       with:
         publish-dir: ./.next
         deploy-message: success deploy
         github-token: ${{secrets.GIT_SECRET}}




