name: develop
on:
 push:
  branches:
    - "develop"
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: lint the code
      run: npm run lint:fix
    - name: Create  build
      run: npm run build

